drop database if exists GENERO;
drop database if exists MUSICA;

CREATE TABLE GENERO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGO CHAR(2),
    NOMBRE VARCHAR(20) NOT NULL,
    CONSTRAINT ID_GENERO_PK PRIMARY KEY (ID)
);

CREATE TABLE MUSICA(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    ALBUM VARCHAR(40) NOT NULL,
    CANTANTE VARCHAR(30),
    GENERO INTEGER NOT NULL,
    FECHA_LANZAMIENTO DATE,
    PRECIO DECIMAL(7,2),
    FAVORITO BOOLEAN,
    FOTO VARCHAR(30),
    CONSTRAINT ID_MUSICA_PK PRIMARY KEY (ID),
    CONSTRAINT GEN_MUSICA_FK FOREIGN KEY (GENERO) REFERENCES GENERO (ID)
);
